### ISSUE TITLE
It is not possible to search without a search expression

### ISSUE THREAD

**Issue by greg-wiltshire** [finos/tracdap#107] opened 2022-02-25 10:05 UTC
### Steps to Reproduce:
Write a search request without a search expression:

```
const searchRequest = trac.api.MetadataSearchRequest.create({
        tenant: tenant,
        searchParams: {
            searchAsOf: searchAsOf,
            objectType: trac.ObjectType.DATA
        }
    })
```

or

```
const searchRequest = trac.api.MetadataSearchRequest.create({
        tenant: tenant,
        searchParams: {
            searchAsOf: searchAsOf,
            objectType: trac.ObjectType.DATA,
            search: undefined
        }
    })
```

### Expected Result:
Without a search term the request should bring back a full list of objects without filtering applied.

### Actual Result:
The request errors.

### Environment:

`trac-web-api": "file:../../../../dev/trac/trac-web-api-0.3.1.tgz`

**Comment by martin-traverse** [comment] 2022-12-09 12:13
Duplicate of #45

**Closed** 2022-12-30 11:24 UTC
