### ISSUE TITLE
Optional inputs and ouputs enabling

### ISSUE THREAD

**Issue by RaluAlexa** [finos/tracdap#169] opened 2022-09-14 09:45 UTC
At the moment, declaring x inputs or outputs in the config means all x need to be returned in the define functions and all outputs are expected after the model run.
Enabling optional outputs will help with cases when the outputs (with different schemas) are dependent on model parameters, and a single one (or subset of all) need to be returned (e.g. scenario runs). Currently this needs to be handled from inside the model code, with conditional outputting based on parameters and empty dataframes being returned for the outputs not produced by that run.

**Comment by martin-traverse** [comment] 2022-12-09 12:23
Duplicate of #137

**Comment by martin-traverse** [comment] 2024-08-21 19:30
PR #442  addresses this issue - inputs and outputs can now be marked as optional in the defined_xxx() methods. To test if an optional input is supplied, use ctx.has_dataset(my_dataset). If an optional output is not required, the model doesn't need to output it. After a model completes, the runtime checks all the non-optional outputs have been provided, but it is fine if optional ones are missing.

Optional inputs and outputs can also be used in flows, either as flow inputs / outputs or to pass between models in the flow.

**Comment by martin-traverse** [comment] 2024-08-21 19:32
Merged PR #442

**Closed by martin-traverse** 2024-08-21 19:32 UTC
