### ISSUE TITLE
Search API can not handle no search criteria

### ISSUE THREAD

**Issue by greg-wiltshire** [finos/tracdap#45] opened 2021-04-08 15:19 UTC
When submitting a search API call with 

```
{
    "objectType": "FLOW",

    "search": {}
}
```
A 500 error is returned. The expected behaviour is that this (or some variant of this) would provide results for all flow objects in TRAC. Without this there is no way to discover what is in TRAC without first knowing the attributes and the values to search for.

**Comment by mslapek** [comment] 2023-01-02 10:59
Is this error still present? 🤔 I think it was solved with #252

**Comment by martin-traverse** [comment] 2023-01-18 16:01
This is a duplicate of #107, closed by #252.

**Closed by martin-traverse** 2023-01-18 16:01 UTC
Labels: bug, duplicate
